language: python
python: 3.6

sudo: required
services: docker

install:
  - "pip3 install -r requirements.txt"

before_install:
  - docker pull faforever/faf-db

before_script:
#  - export MYSQL_ROOT_PASSWORD=banana
#  - export FAF_AIO_REPLAYSERVER_USER=root
#  - export MYSQL_AIO_REPLAYSERVER_PASSWORD=banana
  - sudo /etc/init.d/mysql stop
  - docker run -d --name faf-db -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root faforever/faf-db
  - sleep 30
  - docker logs faf-db

script:
  - MYSQL_HOST=127.0.0.1 ./test.sh

after_success:
  # - export REPO=faforever/faf-aio-replayserver
  # - if [ -n "${TRAVIS_TAG}" ]; then
  #     docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
  #     docker tag faf-aio-replayserver ${REPO}:${TRAVIS_TAG};
  #     docker push ${REPO};
  #   fi
  - coveralls
